# Rails:
#   Enabled: true

AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - db/schema.rb
    - db/migrate/**/*
    - node_modules/**/*
    - bin/**/*
    - 'config/environments/**/*'
    - public/uploads/attachment/**/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/controllers/*'
    - 'spec/acceptance/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
